[package]
name = "PVZbyRust"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15" # now is 25.3.21,but the newest version is 0.16.0-rc.1
rand = "0.9.0"  
[profile.dev]
opt-level = 1 #意味开发配置文件时启用少量基本优化

[profile.dev.package."*"]
opt-level = 3 #对项目所有依赖在开发配置文件中启用大量优化